#define workflow
name: Deployment using multiple jobs
#event that triggers workflow
on: push
#jobs
jobs:
  # name of JOB-1
  lint:
    #specify runner for the job
    runs-on: ubuntu-latest
    #Steps
    steps:
      #STEP-1
      - name: Get Code
        uses: actions/checkout@v3
      #STEP-2
      - name: Install Dependencies
        run: npm ci
      #STEP-3
      - name: Lint
        run: npm run lint
  # name of JOB-2
  test:
    #specify runner for the job
    runs-on: ubuntu-latest
    #Steps
    steps:
      #STEP-1
      - name: Get Code
        uses: actions/checkout@v3
      #STEP-2
      - name: Install Dependencies
        run: npm ci
      #STEP-3
      - name: Test
        run: npm run test
  # name of JOB-3
  deploy:
    #specify runner for the job
    runs-on: ubuntu-latest
    #Steps
    steps:
      #STEP-1
      - name: Get Code
        uses: actions/checkout@v3
      #STEP-2
      - name: Install Dependencies
        run: npm ci
      #STEP-3
      - name: Deploy Code
        run: echo "Deploying..."
